project_id = "cdcoukzjumcfwskkcxkr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[edge_functions]
enabled = true
port = 54326

[functions.upload-document]
verify_jwt = false

[functions.create-partner-with-auth]
verify_jwt = false

[functions.manage-user]
verify_jwt = true

[functions.cleanup-auth-users]
verify_jwt = true

[functions.validate-document]
verify_jwt = false

[functions.classify-document]
verify_jwt = false

[functions.setup-admin-user]
verify_jwt = false

[functions.create-lead-quick]
verify_jwt = true

[functions.verify-student-otp]
verify_jwt = false

[functions.create-lead-student]
verify_jwt = false

[functions.suggest-lender]
verify_jwt = true
